name: build

on:
  push:
    branches:
    - '**'

jobs:
  test:
    runs-on:  windows-11-arm

    steps:
    - uses: actions/checkout@v6

    - name: Environment
      shell: bash
      run: |
        env | sort
        which go
        go env
        which gcc && gcc --version
        which clang && clang --version
        clang -dM -E -x c nul: || true

 
